aria2:
  build: aria2-alpine/.
  ports:
    - "6882:6882/udp"
    - "6881:6881"
    - "6800:6800"
  volumes:
    # - /data/files/aria2Files/:/root/downloads:rw
    - ./aria2Files/:/root/downloads:rw
  restart: always
  container_name: aria2
